# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .asset import Asset
    from .cep_validation_data import CepValidationData
    from .cep_validation_data_amount import CepValidationDataAmount
    from .cep_validation_data_amount_currency import CepValidationDataAmountCurrency
    from .cep_validation_data_beneficiary import CepValidationDataBeneficiary
    from .cep_validation_data_beneficiary_account_type import CepValidationDataBeneficiaryAccountType
    from .cep_validation_data_sender import CepValidationDataSender
    from .cep_validation_data_sender_account_type import CepValidationDataSenderAccountType
    from .cep_validation_data_spei import CepValidationDataSpei
    from .cep_validation_data_timeline import CepValidationDataTimeline
    from .envelope import Envelope
    from .envelope_status import EnvelopeStatus
    from .error_detail import ErrorDetail
    from .face_match_data import FaceMatchData
    from .face_match_data_selfie_analysis import FaceMatchDataSelfieAnalysis
    from .face_match_data_selfie_analysis_detection_confidence import FaceMatchDataSelfieAnalysisDetectionConfidence
    from .face_match_data_selfie_analysis_image_quality import FaceMatchDataSelfieAnalysisImageQuality
    from .face_match_data_selfie_analysis_issues_item import FaceMatchDataSelfieAnalysisIssuesItem
    from .face_match_data_selfie_analysis_orientation import FaceMatchDataSelfieAnalysisOrientation
    from .isste_record_data import IssteRecordData
    from .isste_record_data_address import IssteRecordDataAddress
    from .isste_record_data_affiliation import IssteRecordDataAffiliation
    from .isste_record_data_affiliation_affiliation_status import IssteRecordDataAffiliationAffiliationStatus
    from .isste_record_data_affiliation_beneficiary_type import IssteRecordDataAffiliationBeneficiaryType
    from .isste_record_data_clinic import IssteRecordDataClinic
    from .isste_record_data_clinic_type import IssteRecordDataClinicType
    from .isste_record_data_contribution_history_item import IssteRecordDataContributionHistoryItem
    from .isste_record_data_employment_item import IssteRecordDataEmploymentItem
    from .isste_record_data_family_item import IssteRecordDataFamilyItem
    from .isste_record_data_family_item_relationship import IssteRecordDataFamilyItemRelationship
    from .isste_record_data_family_item_status import IssteRecordDataFamilyItemStatus
    from .isste_record_data_fovisste_history_item import IssteRecordDataFovissteHistoryItem
    from .isste_record_data_pension_regime import IssteRecordDataPensionRegime
    from .isste_record_data_pension_regime_scheme import IssteRecordDataPensionRegimeScheme
    from .isste_record_data_pensions_item import IssteRecordDataPensionsItem
    from .isste_record_data_pensions_item_category import IssteRecordDataPensionsItemCategory
    from .isste_record_data_personal_info import IssteRecordDataPersonalInfo
    from .isste_record_data_personal_info_gender import IssteRecordDataPersonalInfoGender
    from .isste_record_data_personal_info_marital_status import IssteRecordDataPersonalInfoMaritalStatus
    from .liveness_data import LivenessData
    from .liveness_data_confidence import LivenessDataConfidence
    from .liveness_data_selfie_analysis import LivenessDataSelfieAnalysis
    from .liveness_data_selfie_analysis_detection_confidence import LivenessDataSelfieAnalysisDetectionConfidence
    from .liveness_data_selfie_analysis_image_quality import LivenessDataSelfieAnalysisImageQuality
    from .liveness_data_selfie_analysis_issues_item import LivenessDataSelfieAnalysisIssuesItem
    from .liveness_data_selfie_analysis_orientation import LivenessDataSelfieAnalysisOrientation
_dynamic_imports: typing.Dict[str, str] = {
    "Asset": ".asset",
    "CepValidationData": ".cep_validation_data",
    "CepValidationDataAmount": ".cep_validation_data_amount",
    "CepValidationDataAmountCurrency": ".cep_validation_data_amount_currency",
    "CepValidationDataBeneficiary": ".cep_validation_data_beneficiary",
    "CepValidationDataBeneficiaryAccountType": ".cep_validation_data_beneficiary_account_type",
    "CepValidationDataSender": ".cep_validation_data_sender",
    "CepValidationDataSenderAccountType": ".cep_validation_data_sender_account_type",
    "CepValidationDataSpei": ".cep_validation_data_spei",
    "CepValidationDataTimeline": ".cep_validation_data_timeline",
    "Envelope": ".envelope",
    "EnvelopeStatus": ".envelope_status",
    "ErrorDetail": ".error_detail",
    "FaceMatchData": ".face_match_data",
    "FaceMatchDataSelfieAnalysis": ".face_match_data_selfie_analysis",
    "FaceMatchDataSelfieAnalysisDetectionConfidence": ".face_match_data_selfie_analysis_detection_confidence",
    "FaceMatchDataSelfieAnalysisImageQuality": ".face_match_data_selfie_analysis_image_quality",
    "FaceMatchDataSelfieAnalysisIssuesItem": ".face_match_data_selfie_analysis_issues_item",
    "FaceMatchDataSelfieAnalysisOrientation": ".face_match_data_selfie_analysis_orientation",
    "IssteRecordData": ".isste_record_data",
    "IssteRecordDataAddress": ".isste_record_data_address",
    "IssteRecordDataAffiliation": ".isste_record_data_affiliation",
    "IssteRecordDataAffiliationAffiliationStatus": ".isste_record_data_affiliation_affiliation_status",
    "IssteRecordDataAffiliationBeneficiaryType": ".isste_record_data_affiliation_beneficiary_type",
    "IssteRecordDataClinic": ".isste_record_data_clinic",
    "IssteRecordDataClinicType": ".isste_record_data_clinic_type",
    "IssteRecordDataContributionHistoryItem": ".isste_record_data_contribution_history_item",
    "IssteRecordDataEmploymentItem": ".isste_record_data_employment_item",
    "IssteRecordDataFamilyItem": ".isste_record_data_family_item",
    "IssteRecordDataFamilyItemRelationship": ".isste_record_data_family_item_relationship",
    "IssteRecordDataFamilyItemStatus": ".isste_record_data_family_item_status",
    "IssteRecordDataFovissteHistoryItem": ".isste_record_data_fovisste_history_item",
    "IssteRecordDataPensionRegime": ".isste_record_data_pension_regime",
    "IssteRecordDataPensionRegimeScheme": ".isste_record_data_pension_regime_scheme",
    "IssteRecordDataPensionsItem": ".isste_record_data_pensions_item",
    "IssteRecordDataPensionsItemCategory": ".isste_record_data_pensions_item_category",
    "IssteRecordDataPersonalInfo": ".isste_record_data_personal_info",
    "IssteRecordDataPersonalInfoGender": ".isste_record_data_personal_info_gender",
    "IssteRecordDataPersonalInfoMaritalStatus": ".isste_record_data_personal_info_marital_status",
    "LivenessData": ".liveness_data",
    "LivenessDataConfidence": ".liveness_data_confidence",
    "LivenessDataSelfieAnalysis": ".liveness_data_selfie_analysis",
    "LivenessDataSelfieAnalysisDetectionConfidence": ".liveness_data_selfie_analysis_detection_confidence",
    "LivenessDataSelfieAnalysisImageQuality": ".liveness_data_selfie_analysis_image_quality",
    "LivenessDataSelfieAnalysisIssuesItem": ".liveness_data_selfie_analysis_issues_item",
    "LivenessDataSelfieAnalysisOrientation": ".liveness_data_selfie_analysis_orientation",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Asset",
    "CepValidationData",
    "CepValidationDataAmount",
    "CepValidationDataAmountCurrency",
    "CepValidationDataBeneficiary",
    "CepValidationDataBeneficiaryAccountType",
    "CepValidationDataSender",
    "CepValidationDataSenderAccountType",
    "CepValidationDataSpei",
    "CepValidationDataTimeline",
    "Envelope",
    "EnvelopeStatus",
    "ErrorDetail",
    "FaceMatchData",
    "FaceMatchDataSelfieAnalysis",
    "FaceMatchDataSelfieAnalysisDetectionConfidence",
    "FaceMatchDataSelfieAnalysisImageQuality",
    "FaceMatchDataSelfieAnalysisIssuesItem",
    "FaceMatchDataSelfieAnalysisOrientation",
    "IssteRecordData",
    "IssteRecordDataAddress",
    "IssteRecordDataAffiliation",
    "IssteRecordDataAffiliationAffiliationStatus",
    "IssteRecordDataAffiliationBeneficiaryType",
    "IssteRecordDataClinic",
    "IssteRecordDataClinicType",
    "IssteRecordDataContributionHistoryItem",
    "IssteRecordDataEmploymentItem",
    "IssteRecordDataFamilyItem",
    "IssteRecordDataFamilyItemRelationship",
    "IssteRecordDataFamilyItemStatus",
    "IssteRecordDataFovissteHistoryItem",
    "IssteRecordDataPensionRegime",
    "IssteRecordDataPensionRegimeScheme",
    "IssteRecordDataPensionsItem",
    "IssteRecordDataPensionsItemCategory",
    "IssteRecordDataPersonalInfo",
    "IssteRecordDataPersonalInfoGender",
    "IssteRecordDataPersonalInfoMaritalStatus",
    "LivenessData",
    "LivenessDataConfidence",
    "LivenessDataSelfieAnalysis",
    "LivenessDataSelfieAnalysisDetectionConfidence",
    "LivenessDataSelfieAnalysisImageQuality",
    "LivenessDataSelfieAnalysisIssuesItem",
    "LivenessDataSelfieAnalysisOrientation",
]
