# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class Asset(UniversalBaseModel):
    """
    Binary asset (image or document) returned inline as base64. The `files` array contains ONLY assets actually produced; an expected-but-unavailable asset is omitted (never null inside the array).
    """

    kind: str = pydantic.Field()
    """
    Semantic asset name (e.g. document, face, signature).
    """

    content_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="contentType"),
        pydantic.Field(
            alias="contentType", description="MIME type (e.g. application/pdf, image/jpeg, application/xml)."
        ),
    ]
    size_bytes: typing_extensions.Annotated[
        int, FieldMetadata(alias="sizeBytes"), pydantic.Field(alias="sizeBytes", description="Decoded size in bytes.")
    ]
    content: str = pydantic.Field()
    """
    Base64-encoded bytes.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
