# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .asset import Asset
from .cep_validation_data_amount import CepValidationDataAmount
from .cep_validation_data_beneficiary import CepValidationDataBeneficiary
from .cep_validation_data_sender import CepValidationDataSender
from .cep_validation_data_spei import CepValidationDataSpei
from .cep_validation_data_timeline import CepValidationDataTimeline


class CepValidationData(UniversalBaseModel):
    """
    Verified SPEI transfer details from the CEP. Null for non-located outcomes (`CEP_NOT_FOUND`) and error types.
    """

    valid: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the transfer is a confirmed, settled payment. True for LIQUIDADO; false for returned, cancelled or in-process.
    """

    banxico_status: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="banxicoStatus"),
        pydantic.Field(
            alias="banxicoStatus",
            default=None,
            description="Raw Banxico payment state. Known values: `LIQUIDADO`, `DEVUELTO`, `CANCELADO`, `EN PROCESO`. Branch on `type`; use this for display.",
        ),
    ]
    tracking_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="trackingKey"),
        pydantic.Field(alias="trackingKey", default=None, description="Clave de rastreo of the transfer."),
    ]
    reference_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="referenceNumber"),
        pydantic.Field(alias="referenceNumber", default=None, description="Reference number, when present in the CEP."),
    ]
    operation_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="operationDate"),
        pydantic.Field(
            alias="operationDate",
            default=None,
            description="Business operation date (ISO `YYYY-MM-DD`). The calendar date used to match; see `timeline.operatedAt` for the exact instant.",
        ),
    ]
    concept: typing.Optional[str] = pydantic.Field(default=None)
    """
    Payment concept, when present.
    """

    amount: typing.Optional[CepValidationDataAmount] = pydantic.Field(default=None)
    """
    Transfer amount. `value` is a decimal string, exact to the cent; currency is always MXN.
    """

    sender: typing.Optional[CepValidationDataSender] = pydantic.Field(default=None)
    """
    Ordering (sender) party. Fields may be null when Banxico does not expose them (for non-settled results).
    """

    beneficiary: typing.Optional[CepValidationDataBeneficiary] = pydantic.Field(default=None)
    """
    Beneficiary party. Fields may be null when Banxico does not expose them (for non-settled results).
    """

    timeline: typing.Optional[CepValidationDataTimeline] = pydantic.Field(default=None)
    """
    Transfer lifecycle timestamps, ISO 8601 in `America/Mexico_City` (`-06:00`), second precision. Null where not applicable to the result.
    """

    spei: typing.Optional[CepValidationDataSpei] = pydantic.Field(default=None)
    """
    SPEI / Banxico cryptographic proof carried by the CEP (the digital signature that makes the CEP verifiable).
    """

    files: typing.Optional[typing.List[Asset]] = pydantic.Field(default=None)
    """
    CEP documents as inline base64 assets. The XML (`application/xml`) is present for settled payments; the PDF (`application/pdf`) is included only when `includePdf` is true. Empty for non-settled results.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
