# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .cep_validation_data_beneficiary_account_type import CepValidationDataBeneficiaryAccountType


class CepValidationDataBeneficiary(UniversalBaseModel):
    """
    Beneficiary party. Fields may be null when Banxico does not expose them (for non-settled results).
    """

    name: typing.Optional[str] = None
    bank_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankCode"),
        pydantic.Field(alias="bankCode", default=None, description="Banxico institution code (5 digits)."),
    ]
    bank_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="bankName"), pydantic.Field(alias="bankName", default=None)
    ]
    account: typing.Optional[str] = None
    account_type: typing_extensions.Annotated[
        typing.Optional[CepValidationDataBeneficiaryAccountType],
        FieldMetadata(alias="accountType"),
        pydantic.Field(
            alias="accountType",
            default=None,
            description="Inferred from the account number (18-digit CLABE or 16-digit card).",
        ),
    ]
    rfc: typing.Optional[str] = pydantic.Field(default=None)
    """
    RFC as printed in the CEP, when present.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
