# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class CepValidationDataTimeline(UniversalBaseModel):
    """
    Transfer lifecycle timestamps, ISO 8601 in `America/Mexico_City` (`-06:00`), second precision. Null where not applicable to the result.
    """

    operated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="operatedAt"),
        pydantic.Field(
            alias="operatedAt", default=None, description="Instant the transfer was operated (from the CEP)."
        ),
    ]
    received_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="receivedAt"),
        pydantic.Field(alias="receivedAt", default=None, description="Instant SPEI received the payment order."),
    ]
    settled_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="settledAt"),
        pydantic.Field(alias="settledAt", default=None, description="Instant SPEI settled the payment (liquidación)."),
    ]
    return_received_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="returnReceivedAt"),
        pydantic.Field(alias="returnReceivedAt", default=None, description="Instant the return order was received."),
    ]
    return_settled_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="returnSettledAt"),
        pydantic.Field(alias="returnSettledAt", default=None, description="Instant the return was settled."),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
