# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .cep_validation_data_amount_currency import CepValidationDataAmountCurrency


class CepValidationDataAmount(UniversalBaseModel):
    """
    Transfer amount. `value` is a decimal string, exact to the cent; currency is always MXN.
    """

    value: typing.Optional[str] = None
    currency: typing.Optional[CepValidationDataAmountCurrency] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
