# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class CepValidationDataSpei(UniversalBaseModel):
    """
    SPEI / Banxico cryptographic proof carried by the CEP (the digital signature that makes the CEP verifiable).
    """

    spei_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="speiKey"),
        pydantic.Field(alias="speiKey", default=None, description="Clave SPEI (operating-institution code)."),
    ]
    certificate_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="certificateNumber"),
        pydantic.Field(alias="certificateNumber", default=None),
    ]
    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    Base64 digital signature from Banxico.
    """

    cda_chain: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cdaChain"),
        pydantic.Field(
            alias="cdaChain", default=None, description="Original signed CDA chain (the string Banxico signed)."
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
