# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .envelope_status import EnvelopeStatus
from .error_detail import ErrorDetail


class Envelope(UniversalBaseModel):
    status: EnvelopeStatus
    type: str = pydantic.Field()
    """
    Stable result type code. Includes generic codes (`SUCCESS`, `INVALID_REQUEST`, `UNAUTHORIZED`, `SERVICE_UNAVAILABLE`, `INTERNAL_ERROR`, `RATE_LIMIT_EXCEEDED`) plus endpoint-specific result codes — see this endpoint's response examples.
    """

    message: str = pydantic.Field()
    """
    Human-readable summary of the result. Always in English (per Language Conventions in the API overview).
    """

    data: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Response payload. `null` on error responses. Shape depends on the endpoint — see each operation's response schema.
    """

    errors: typing.Optional[typing.List[ErrorDetail]] = pydantic.Field(default=None)
    """
    Per-field error details. Present only on `INVALID_REQUEST` responses.
    """

    transaction_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="transactionId"),
        pydantic.Field(
            alias="transactionId",
            description="Unique identifier of this request, generated by the API Gateway. Propagated end-to-end for traceability.",
        ),
    ]
    processed_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="processedAt"),
        pydantic.Field(
            alias="processedAt",
            description="ISO 8601 datetime with Mexico City offset (`-06:00`). Always set by the API Gateway when the response leaves the system.",
        ),
    ]
    billable: bool = pydantic.Field()
    """
    Whether this request will be charged against the client's plan. Typically `true` for successful business results and `false` for validation errors or system errors that prevented processing.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
