# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .envelope_status import EnvelopeStatus
import pydantic
import typing
from .error_detail import ErrorDetail
import typing_extensions
from ..core.serialization import FieldMetadata
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Envelope(UniversalBaseModel):
    status: EnvelopeStatus = pydantic.Field()
    """
    High-level outcome. `OK` means the request was successfully processed (regardless of business result). `ERROR` means the request was rejected or could not be processed.
    """

    type: str = pydantic.Field()
    """
    Stable result type code. Catalog includes generic (`SUCCESS`, `INVALID_REQUEST`, `UNAUTHORIZED`, `SERVICE_UNAVAILABLE`, `INTERNAL_ERROR`, `RATE_LIMIT_EXCEEDED`) plus endpoint-specific codes (`CURP_NOT_FOUND`, `CFDI_CANCELED`, etc.).
    """

    message: str = pydantic.Field()
    """
    Human-readable summary of the result. Always in English (per Language Conventions in the API overview).
    """

    data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Response payload. `null` on error responses. Shape depends on the endpoint — see each operation's response schema.
    """

    errors: typing.Optional[typing.List[ErrorDetail]] = pydantic.Field(default=None)
    """
    Per-field error details. Present only on `INVALID_REQUEST` responses.
    """

    transaction_id: typing_extensions.Annotated[str, FieldMetadata(alias="transactionId")] = pydantic.Field()
    """
    Unique identifier of this request, generated by the API Gateway. Propagated end-to-end for traceability.
    """

    processed_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="processedAt")] = pydantic.Field()
    """
    ISO 8601 datetime with Mexico City offset (`-06:00`). Always set by the API Gateway when the response leaves the system.
    """

    billable: bool = pydantic.Field()
    """
    Whether this request will be charged against the client's plan. Typically `true` for successful business results and `false` for validation errors or system errors that prevented processing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
