# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ErrorDetail(UniversalBaseModel):
    field: str = pydantic.Field()
    """
    JSON path or field name where the validation failed. Use `requestBody` for top-level errors.
    """

    code: str = pydantic.Field()
    """
    Machine-readable error code. Examples: `MISSING_REQUIRED_FIELD`, `INVALID_FORMAT`, `INVALID_VALUE`, `INVALID_ENUM_VALUE`.
    """

    message: str = pydantic.Field()
    """
    Human-readable description of the field-level error.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
