# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .face_match_data_selfie_analysis import FaceMatchDataSelfieAnalysis


class FaceMatchData(UniversalBaseModel):
    """
    Face-match result. Null for `INVALID_REQUEST` and `INTERNAL_ERROR`.
    """

    face_match_score: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="faceMatchScore"),
        pydantic.Field(
            alias="faceMatchScore",
            default=None,
            description="Similarity 0-100. Null when the score was not the basis of the result (DOCUMENT_MISMATCH, NO_DOCUMENT_DETECTED, NO_FACE_DETECTED, MULTIPLE_FACES_DETECTED) — anti-leak of signal.",
        ),
    ]
    is_match: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isMatch"), pydantic.Field(alias="isMatch", default=None)
    ]
    threshold_applied: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="thresholdApplied"),
        pydantic.Field(
            alias="thresholdApplied",
            default=None,
            description="Threshold used for the decision. Null when not applied (non-match outcomes).",
        ),
    ]
    detected_document_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="detectedDocumentType"),
        pydantic.Field(
            alias="detectedDocumentType",
            default=None,
            description="Document type classified from the front image (e.g. `INE`, `MEX_PASSPORT`, `OTHER`). Null in some non-match cases.",
        ),
    ]
    selfie_analysis: typing_extensions.Annotated[
        typing.Optional[FaceMatchDataSelfieAnalysis],
        FieldMetadata(alias="selfieAnalysis"),
        pydantic.Field(
            alias="selfieAnalysis",
            default=None,
            description="Quality/attribute labels of the selfie face (DX-friendly, no raw scores). Null when there is no single selfie face (NO_FACE_DETECTED on selfie, MULTIPLE_FACES_DETECTED).",
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
