# This file was auto-generated by Fern from our API Definition.

import typing

FaceMatchDataSelfieAnalysisOrientation = typing.Union[
    typing.Literal["front", "looking_left", "looking_right", "looking_up", "looking_down", "tilted", "sideways"],
    typing.Any,
]
