# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .isste_record_data_personal_info_gender import IssteRecordDataPersonalInfoGender
from .isste_record_data_personal_info_marital_status import IssteRecordDataPersonalInfoMaritalStatus


class IssteRecordDataPersonalInfo(UniversalBaseModel):
    curp: typing.Optional[str] = None
    given_names: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="givenNames"), pydantic.Field(alias="givenNames", default=None)
    ]
    first_surname: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="firstSurname"), pydantic.Field(alias="firstSurname", default=None)
    ]
    second_surname: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="secondSurname"), pydantic.Field(alias="secondSurname", default=None)
    ]
    rfc: typing.Optional[str] = pydantic.Field(default=None)
    """
    RFC as printed in the record. May be incomplete (10-char base without homoclave) or empty when the source PDF omits it.
    """

    gender: typing.Optional[IssteRecordDataPersonalInfoGender] = pydantic.Field(default=None)
    """
    Normalized from source HOMBRE/MUJER.
    """

    date_of_birth: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="dateOfBirth"),
        pydantic.Field(
            alias="dateOfBirth", default=None, description="ISO `YYYY-MM-DD` (normalized from source DD/MM/YYYY)."
        ),
    ]
    marital_status: typing_extensions.Annotated[
        typing.Optional[IssteRecordDataPersonalInfoMaritalStatus],
        FieldMetadata(alias="maritalStatus"),
        pydantic.Field(
            alias="maritalStatus",
            default=None,
            description="Civil status, normalized (source prints a gender-neutral '(A)' suffix, removed here). `null` when ISSSTE does not report it. Only SOLTERO/CASADO seen in the current corpus.",
        ),
    ]
    nss: typing.Optional[str] = pydantic.Field(default=None)
    """
    Social security number (NSS).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
