# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class IssteRecordDataAddress(UniversalBaseModel):
    """
    Domicilio.
    """

    street: typing.Optional[str] = None
    exterior_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="exteriorNumber"),
        pydantic.Field(alias="exteriorNumber", default=None),
    ]
    interior_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="interiorNumber"),
        pydantic.Field(alias="interiorNumber", default=None),
    ]
    neighborhood: typing.Optional[str] = pydantic.Field(default=None)
    """
    Colonia.
    """

    municipality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Delegación / municipio.
    """

    state: typing.Optional[str] = None
    postal_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="postalCode"), pydantic.Field(alias="postalCode", default=None)
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
