# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class IssteRecordDataFovissteHistoryItem(UniversalBaseModel):
    agency: typing.Optional[str] = None
    payroll_office: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="payrollOffice"), pydantic.Field(alias="payrollOffice", default=None)
    ]
    period_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="periodType"), pydantic.Field(alias="periodType", default=None)
    ]
    start_date: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="startDate"), pydantic.Field(alias="startDate", default=None)
    ]
    end_date: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="endDate"), pydantic.Field(alias="endDate", default=None)
    ]
    base_salary: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="baseSalary"),
        pydantic.Field(alias="baseSalary", default=None, description="Sueldo básico (MXN)."),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
