# This file was auto-generated by Fern from our API Definition.

import typing

IssteRecordDataPensionsItemCategory = typing.Union[
    typing.Literal["DIRECT", "SURVIVOR", "INSURANCE", "DISABILITY"], typing.Any
]
