# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class IssteRecordDataEmploymentItem(UniversalBaseModel):
    agency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Ramo / government agency.
    """

    payroll_office: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="payrollOffice"),
        pydantic.Field(alias="payrollOffice", default=None, description="Pagaduría."),
    ]
    start_date: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="startDate"), pydantic.Field(alias="startDate", default=None)
    ]
    base_salary: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="baseSalary"),
        pydantic.Field(alias="baseSalary", default=None, description="Salario base de cotización (MXN)."),
    ]
    position_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="positionType"),
        pydantic.Field(
            alias="positionType", default=None, description="Tipo de plaza/pensión (e.g. CONFIANZA, BECARIO)."
        ),
    ]
    total_compensation: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="totalCompensation"),
        pydantic.Field(alias="totalCompensation", default=None, description="Remuneración total (MXN)."),
    ]
    coverage: typing.Optional[str] = pydantic.Field(default=None)
    """
    Modalidad de seguros/prestaciones (source field `modilidad` [sic] corrected to `coverage`).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
