# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .isste_record_data_family_item_relationship import IssteRecordDataFamilyItemRelationship
from .isste_record_data_family_item_status import IssteRecordDataFamilyItemStatus


class IssteRecordDataFamilyItem(UniversalBaseModel):
    curp: typing.Optional[str] = None
    first_surname: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="firstSurname"), pydantic.Field(alias="firstSurname", default=None)
    ]
    second_surname: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="secondSurname"), pydantic.Field(alias="secondSurname", default=None)
    ]
    given_names: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="givenNames"), pydantic.Field(alias="givenNames", default=None)
    ]
    relationship: typing.Optional[IssteRecordDataFamilyItemRelationship] = pydantic.Field(default=None)
    """
    Parentesco (official raw value).
    """

    status: typing.Optional[IssteRecordDataFamilyItemStatus] = pydantic.Field(default=None)
    """
    Derechohabiencia status of the family member (raw).
    """

    date_of_birth: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="dateOfBirth"), pydantic.Field(alias="dateOfBirth", default=None)
    ]
    registration_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="registrationDate"),
        pydantic.Field(alias="registrationDate", default=None, description="Fecha de alta as a dependant."),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
