# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .isste_record_data_pensions_item_category import IssteRecordDataPensionsItemCategory


class IssteRecordDataPensionsItem(UniversalBaseModel):
    category: typing.Optional[IssteRecordDataPensionsItemCategory] = pydantic.Field(default=None)
    """
    Derived pension class from the payroll office: DIRECT (own retirement, pagaduria DIRECTOS), SURVIVOR (deudos), INSURANCE (cuenta individual aseguradora), DISABILITY (ITP/IPP).
    """

    agency: typing.Optional[str] = None
    payroll_office: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="payrollOffice"), pydantic.Field(alias="payrollOffice", default=None)
    ]
    start_date: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="startDate"), pydantic.Field(alias="startDate", default=None)
    ]
    pension_number: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="pensionNumber"), pydantic.Field(alias="pensionNumber", default=None)
    ]
    pension_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="pensionType"),
        pydantic.Field(
            alias="pensionType",
            default=None,
            description="Numeric ISSSTE pension-type code (e.g. `101` retirement, `316` survivor). 21+ codes.",
        ),
    ]
    pension_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="pensionAmount"),
        pydantic.Field(alias="pensionAmount", default=None, description="Monthly pension amount (MXN)."),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
