# This file was auto-generated by Fern from our API Definition.

import typing

IssteRecordDataAffiliationAffiliationStatus = typing.Union[
    typing.Literal["ACTIVO", "INACTIVO", "FINADO", ""], typing.Any
]
