# This file was auto-generated by Fern from our API Definition.

import typing

IssteRecordDataFamilyItemRelationship = typing.Union[
    typing.Literal[
        "HIJO",
        "HIJA",
        "ESPOSO",
        "ESPOSA",
        "CONCUBINA",
        "CONCUBINO",
        "MADRE",
        "PADRE",
        "ABUELA",
        "ABUELO",
        "HIJA DE CONYUGE",
    ],
    typing.Any,
]
