# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .isste_record_data_clinic_type import IssteRecordDataClinicType


class IssteRecordDataClinic(UniversalBaseModel):
    """
    Assigned medical unit (clínica de adscripción).
    """

    code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Clave.
    """

    type: typing.Optional[IssteRecordDataClinicType] = pydantic.Field(default=None)
    """
    Medical-unit type (raw).
    """

    name: typing.Optional[str] = None
    address: typing.Optional[str] = None
    isste_delegation: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="issteDelegation"),
        pydantic.Field(alias="issteDelegation", default=None),
    ]
    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    May be `NO DISPONIBLE` or comma-separated numbers.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
