# This file was auto-generated by Fern from our API Definition.

import typing

IssteRecordDataClinicType = typing.Union[
    typing.Literal["CMF", "UMF", "CMFE", "CH", "CAF", "HAE", "HG", "CMFEQ"], typing.Any
]
