# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .isste_record_data_affiliation_affiliation_status import IssteRecordDataAffiliationAffiliationStatus
from .isste_record_data_affiliation_beneficiary_type import IssteRecordDataAffiliationBeneficiaryType


class IssteRecordDataAffiliation(UniversalBaseModel):
    beneficiary_type: typing_extensions.Annotated[
        typing.Optional[IssteRecordDataAffiliationBeneficiaryType],
        FieldMetadata(alias="beneficiaryType"),
        pydantic.Field(
            alias="beneficiaryType",
            default=None,
            description="Authoritative standing, derived from the record: a holder of a DIRECT pension is reported as PENSIONISTA even when the source document labels them TRABAJADOR. ISSSTE only exposes titulares.",
        ),
    ]
    affiliation_status: typing_extensions.Annotated[
        typing.Optional[IssteRecordDataAffiliationAffiliationStatus],
        FieldMetadata(alias="affiliationStatus"),
        pydantic.Field(
            alias="affiliationStatus", default=None, description="Raw official value. Empty string when not reported."
        ),
    ]
    government_entry_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="governmentEntryDate"),
        pydantic.Field(
            alias="governmentEntryDate",
            default=None,
            description="Date the worker entered federal government employment (ISO).",
        ),
    ]
    current_position_start_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="currentPositionStartDate"),
        pydantic.Field(alias="currentPositionStartDate", default=None),
    ]
    termination_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="terminationDate"),
        pydantic.Field(
            alias="terminationDate", default=None, description="`null` while `ACTIVO`; set for `INACTIVO`/`FINADO`."
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
