# This file was auto-generated by Fern from our API Definition.

import typing

IssteRecordDataFamilyItemStatus = typing.Union[
    typing.Literal["ACTIVO", "SIN DERECHO", "EN CONSERVACIÓN DE DERECHOS", "POSIBLE DEUDO"], typing.Any
]
