# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .asset import Asset
from .isste_record_data_address import IssteRecordDataAddress
from .isste_record_data_affiliation import IssteRecordDataAffiliation
from .isste_record_data_clinic import IssteRecordDataClinic
from .isste_record_data_contribution_history_item import IssteRecordDataContributionHistoryItem
from .isste_record_data_employment_item import IssteRecordDataEmploymentItem
from .isste_record_data_family_item import IssteRecordDataFamilyItem
from .isste_record_data_fovisste_history_item import IssteRecordDataFovissteHistoryItem
from .isste_record_data_pension_regime import IssteRecordDataPensionRegime
from .isste_record_data_pensions_item import IssteRecordDataPensionsItem
from .isste_record_data_personal_info import IssteRecordDataPersonalInfo


class IssteRecordData(UniversalBaseModel):
    """
    Full ISSSTE record for a government worker. Present only when `type` is `SUCCESS`.
    """

    personal_info: typing_extensions.Annotated[
        typing.Optional[IssteRecordDataPersonalInfo],
        FieldMetadata(alias="personalInfo"),
        pydantic.Field(alias="personalInfo", default=None),
    ]
    affiliation: typing.Optional[IssteRecordDataAffiliation] = None
    pension_regime: typing_extensions.Annotated[
        typing.Optional[IssteRecordDataPensionRegime],
        FieldMetadata(alias="pensionRegime"),
        pydantic.Field(alias="pensionRegime", default=None),
    ]
    employment: typing.Optional[typing.List[IssteRecordDataEmploymentItem]] = pydantic.Field(default=None)
    """
    Worker positions (PLAZAS TRABAJADOR). Empty for PENSIONISTA or INACTIVO without an active position.
    """

    pensions: typing.Optional[typing.List[IssteRecordDataPensionsItem]] = pydantic.Field(default=None)
    """
    Pension records (survivor/retirement pensions, PENSIONES). Empty when none.
    """

    contribution_history: typing_extensions.Annotated[
        typing.Optional[typing.List[IssteRecordDataContributionHistoryItem]],
        FieldMetadata(alias="contributionHistory"),
        pydantic.Field(
            alias="contributionHistory",
            default=None,
            description="Contribution (cotización) timeline. May be empty for `INACTIVO` without archived data.",
        ),
    ]
    fovisste_history: typing_extensions.Annotated[
        typing.Optional[typing.List[IssteRecordDataFovissteHistoryItem]],
        FieldMetadata(alias="fovissteHistory"),
        pydantic.Field(
            alias="fovissteHistory",
            default=None,
            description="FOVISSSTE contribution history (housing fund) — HISTORIAL DE COTIZACIÓN FOVISSSTE. Same shape as contributionHistory; may mirror it or be a subset.",
        ),
    ]
    family: typing.Optional[typing.List[IssteRecordDataFamilyItem]] = pydantic.Field(default=None)
    """
    Registered family members / dependants (FAMILIARES). Empty when none.
    """

    address: typing.Optional[IssteRecordDataAddress] = pydantic.Field(default=None)
    """
    Domicilio.
    """

    clinic: typing.Optional[IssteRecordDataClinic] = pydantic.Field(default=None)
    """
    Assigned medical unit (clínica de adscripción).
    """

    files: typing.Optional[typing.List[Asset]] = pydantic.Field(default=None)
    """
    Binary assets (inline base64). The document (PDF) is always present. A face is included only when the record contains a usable face; it is omitted when no face is present or its quality is too low.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
