# This file was auto-generated by Fern from our API Definition.

import typing

IssteRecordDataPensionRegimeScheme = typing.Union[
    typing.Literal["CUENTAS INDIVIDUALES", "DÉCIMO TRANSITORIO", "SIN RÉGIMEN", ""], typing.Any
]
