# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .liveness_data_confidence import LivenessDataConfidence
from .liveness_data_selfie_analysis import LivenessDataSelfieAnalysis


class LivenessData(UniversalBaseModel):
    """
    Liveness result. Null for `INVALID_REQUEST`, `INTERNAL_ERROR` and `SERVICE_UNAVAILABLE`. On every `OK` outcome the object is present: when nothing could be evaluated (`NO_FACE_DETECTED`, `MULTIPLE_FACES_DETECTED`, `IMAGE_UNREADABLE`) `isLive` is `false` and the remaining fields are null.
    """

    is_live: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isLive"),
        pydantic.Field(
            alias="isLive",
            default=None,
            description="`true` when `livenessScore` reaches the decision threshold (62). Always present; `false` when the image was not evaluated.",
        ),
    ]
    liveness_score: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="livenessScore"),
        pydantic.Field(
            alias="livenessScore",
            default=None,
            description="Fused anti-spoofing score, 0–100. Null when the image was not evaluated.",
        ),
    ]
    confidence: typing.Optional[LivenessDataConfidence] = pydantic.Field(default=None)
    """
    Distance of the score from the decision threshold: `HIGH` 25 points or more, `MEDIUM` 10 or more, `LOW` otherwise. Null when the image was not evaluated.
    """

    selfie_analysis: typing_extensions.Annotated[
        typing.Optional[LivenessDataSelfieAnalysis],
        FieldMetadata(alias="selfieAnalysis"),
        pydantic.Field(
            alias="selfieAnalysis",
            default=None,
            description="Quality/attribute labels of the evaluated face — the largest face when `allowMultipleFaces` is true. Same shape as `matchFaces`. Null when the image was not evaluated or when face analysis was unavailable.",
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
