# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .liveness_data_selfie_analysis_detection_confidence import LivenessDataSelfieAnalysisDetectionConfidence
from .liveness_data_selfie_analysis_image_quality import LivenessDataSelfieAnalysisImageQuality
from .liveness_data_selfie_analysis_issues_item import LivenessDataSelfieAnalysisIssuesItem
from .liveness_data_selfie_analysis_orientation import LivenessDataSelfieAnalysisOrientation


class LivenessDataSelfieAnalysis(UniversalBaseModel):
    """
    Quality/attribute labels of the evaluated face — the largest face when `allowMultipleFaces` is true. Same shape as `matchFaces`. Null when the image was not evaluated or when face analysis was unavailable.
    """

    image_quality: typing_extensions.Annotated[
        typing.Optional[LivenessDataSelfieAnalysisImageQuality],
        FieldMetadata(alias="imageQuality"),
        pydantic.Field(
            alias="imageQuality",
            default=None,
            description="`excellent`: brightness ≥ 75 and sharpness ≥ 75 · `good`: both ≥ 50 · `poor`: otherwise (in practice, usually a dark image rather than an out-of-focus one).",
        ),
    ]
    detection_confidence: typing_extensions.Annotated[
        typing.Optional[LivenessDataSelfieAnalysisDetectionConfidence],
        FieldMetadata(alias="detectionConfidence"),
        pydantic.Field(
            alias="detectionConfidence",
            default=None,
            description="Provider confidence that the detection is a face: `high` ≥ 95 · `medium` ≥ 80 · `low` below 80.",
        ),
    ]
    orientation: typing.Optional[LivenessDataSelfieAnalysisOrientation] = pydantic.Field(default=None)
    """
    Evaluated in order, first match wins: `sideways` abs(yaw) ≥ 25° · `looking_left` yaw ≥ 10° · `looking_right` yaw ≤ −10° · `looking_up` pitch ≥ 20° · `looking_down` pitch ≤ −20° · `tilted` abs(roll) ≥ 15° · otherwise `front`.
    """

    eyes_open: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="eyesOpen"),
        pydantic.Field(alias="eyesOpen", default=None, description="Null when the attribute could not be determined."),
    ]
    mouth_open: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="mouthOpen"),
        pydantic.Field(
            alias="mouthOpen",
            default=None,
            description="Informational; never produces an issue. Null when the attribute could not be determined.",
        ),
    ]
    wearing_glasses: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="wearingGlasses"),
        pydantic.Field(
            alias="wearingGlasses", default=None, description="Null when the attribute could not be determined."
        ),
    ]
    wearing_sunglasses: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="wearingSunglasses"),
        pydantic.Field(
            alias="wearingSunglasses", default=None, description="Null when the attribute could not be determined."
        ),
    ]
    face_covered: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="faceCovered"),
        pydantic.Field(
            alias="faceCovered", default=None, description="Null when the attribute could not be determined."
        ),
    ]
    issues: typing.Optional[typing.List[LivenessDataSelfieAnalysisIssuesItem]] = pydantic.Field(default=None)
    """
    Every condition detected on the face; empty when none. All possible values: `poor_image_quality` (`imageQuality` is `poor`) · `not_facing_camera` (`orientation` is not `front`) · `eyes_closed` (`eyesOpen` is `false`) · `face_covered` (`faceCovered` is `true`) · `wearing_glasses` (`wearingGlasses` is `true`, informational) · `wearing_sunglasses` (`wearingSunglasses` is `true`) · `low_detection_confidence` (`detectionConfidence` is `low`). Retry hints, not rejection criteria.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
