# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.match_faces_request_document_type import MatchFacesRequestDocumentType
from ..core.request_options import RequestOptions
from ..types.envelope import Envelope
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.too_many_requests_error import TooManyRequestsError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BiometricsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def match_faces(
        self,
        *,
        face: str,
        front: str,
        threshold: typing.Optional[int] = OMIT,
        document_type: typing.Optional[MatchFacesRequestDocumentType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Compares two facial images and returns a similarity score (0–100) plus a binary match/no-match decision. Typical use is 1:1 verification between a live selfie and the photograph on an ID document.

        Use this endpoint to confirm that the person presenting an ID is the same person depicted on it. Combine with `checkLiveness` to also defend against presentation attacks (photo of a photo, printed mask).

        Parameters
        ----------
        face : str
            Face image (selfie) in Base64 (PNG/JPG)

        front : str
            Front ID image in Base64 (PNG/JPG). Can be any official document globally.

        threshold : typing.Optional[int]
            Acceptance threshold (1-100). Default: 80.

        document_type : typing.Optional[MatchFacesRequestDocumentType]
            Optional. Use a specific type (e.g., 'INE', 'MEX_PASSPORT') for strict validation against that exact document type. Use 'ANY' to require the image be SOME recognized ID (auto-detected) — returns NO_DOCUMENT_DETECTED if not. Omit entirely for permissive mode (face match only, no document validation — intended for non-KYC use cases).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Biometric analysis result (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.biometrics.match_faces(
            face="face",
            front="front",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/face-matches",
            method="POST",
            json={
                "face": face,
                "front": front,
                "threshold": threshold,
                "documentType": document_type,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def check_liveness(self, *, selfie: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Analyzes a selfie to determine whether it depicts a real, live person in front of the camera (`isLive: true`) or a spoofing attempt (printed photo, screen replay, mask). Returns a liveness score, confidence level, and detected attack types when applicable.

        Use this endpoint at the start of a remote KYC flow to filter out automated bots, recycled images, and basic presentation attacks before invoking heavier downstream checks.

        Parameters
        ----------
        selfie : str
            Selfie image of the subject in Base64 (PNG/JPG).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Liveness analysis result (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.biometrics.check_liveness(
            selfie="selfie",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/liveness-checks",
            method="POST",
            json={
                "selfie": selfie,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncBiometricsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def match_faces(
        self,
        *,
        face: str,
        front: str,
        threshold: typing.Optional[int] = OMIT,
        document_type: typing.Optional[MatchFacesRequestDocumentType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Compares two facial images and returns a similarity score (0–100) plus a binary match/no-match decision. Typical use is 1:1 verification between a live selfie and the photograph on an ID document.

        Use this endpoint to confirm that the person presenting an ID is the same person depicted on it. Combine with `checkLiveness` to also defend against presentation attacks (photo of a photo, printed mask).

        Parameters
        ----------
        face : str
            Face image (selfie) in Base64 (PNG/JPG)

        front : str
            Front ID image in Base64 (PNG/JPG). Can be any official document globally.

        threshold : typing.Optional[int]
            Acceptance threshold (1-100). Default: 80.

        document_type : typing.Optional[MatchFacesRequestDocumentType]
            Optional. Use a specific type (e.g., 'INE', 'MEX_PASSPORT') for strict validation against that exact document type. Use 'ANY' to require the image be SOME recognized ID (auto-detected) — returns NO_DOCUMENT_DETECTED if not. Omit entirely for permissive mode (face match only, no document validation — intended for non-KYC use cases).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Biometric analysis result (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.biometrics.match_faces(
                face="face",
                front="front",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/face-matches",
            method="POST",
            json={
                "face": face,
                "front": front,
                "threshold": threshold,
                "documentType": document_type,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def check_liveness(self, *, selfie: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Analyzes a selfie to determine whether it depicts a real, live person in front of the camera (`isLive: true`) or a spoofing attempt (printed photo, screen replay, mask). Returns a liveness score, confidence level, and detected attack types when applicable.

        Use this endpoint at the start of a remote KYC flow to filter out automated bots, recycled images, and basic presentation attacks before invoking heavier downstream checks.

        Parameters
        ----------
        selfie : str
            Selfie image of the subject in Base64 (PNG/JPG).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Liveness analysis result (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.biometrics.check_liveness(
                selfie="selfie",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/liveness-checks",
            method="POST",
            json={
                "selfie": selfie,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
