# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.envelope import Envelope
from .types.check_liveness_response import CheckLivenessResponse
from .types.match_faces_request_document_type import MatchFacesRequestDocumentType
from .types.match_faces_response import MatchFacesResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawBiometricsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def match_faces(
        self,
        *,
        face: str,
        front: str,
        threshold: typing.Optional[int] = OMIT,
        document_type: typing.Optional[MatchFacesRequestDocumentType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MatchFacesResponse]:
        """
        **Credits:** 1 per call.

        Compares two facial images and returns a similarity score (0–100) plus a binary match/no-match decision. Typical use is 1:1 verification between a live selfie and the photograph on an ID document.

        Use this endpoint to confirm that the person presenting an ID is the same person depicted on it.

        Parameters
        ----------
        face : str
            Face image (selfie) in Base64 (PNG/JPG)

        front : str
            Front ID image in Base64 (PNG/JPG). Can be any official document globally.

        threshold : typing.Optional[int]
            Acceptance threshold (1-100). Default: **90** (KYC-grade). Lower (e.g. 80) is more permissive; higher is stricter. Overridable per request.

        document_type : typing.Optional[MatchFacesRequestDocumentType]
            Optional. Use a specific type (e.g. `INE`, `MEX_PASSPORT`) for strict validation against that exact document type. Use `ANY` to require the image be some recognized ID (auto-detected) — returns `NO_DOCUMENT_DETECTED` if not. Omit it to skip document validation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MatchFacesResponse]
            Biometric analysis result (Strict Envelope Pattern).
        """
        _response = self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/face-matches",
            method="POST",
            json={
                "face": face,
                "front": front,
                "threshold": threshold,
                "documentType": document_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MatchFacesResponse,
                    parse_obj_as(
                        type_=MatchFacesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def check_liveness(
        self,
        *,
        selfie: str,
        allow_multiple_faces: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CheckLivenessResponse]:
        """
        **Credits:** 1 per call.

        Determines whether a selfie shows a real, live person in front of the camera (`isLive: true`) or a spoofing attempt (`isLive: false`).

        Returns:

        - **`isLive`**: the decision. `livenessScore` (0–100) is the fused output of the anti-spoofing models; the decision threshold is **62**.
        - **`confidence`**: how far the score landed from the threshold — `HIGH` (25 points or more), `MEDIUM` (10 or more) or `LOW`.
        - **`selfieAnalysis`**: quality and attribute labels of the evaluated face (image quality, orientation, eyes open, glasses, face covered, actionable `issues[]`). Same object as `matchFaces`, so both endpoints share one integration.

        **Multiple people in frame.** By default a selfie with another person present returns `MULTIPLE_FACES_DETECTED`. Send `allowMultipleFaces: true` to evaluate the largest face in the image instead (the person holding the phone); `selfieAnalysis` describes that same face. Only faces of at least 25% of the main face's area count as another person — people in the background do not.

        **Decision rule.** Accept only `type: SUCCESS` with `isLive: true`. `NO_FACE_DETECTED`, `MULTIPLE_FACES_DETECTED` and `IMAGE_UNREADABLE` also return `isLive: false`, but nothing was evaluated — `data` always carries the full object so you can read `data.isLive` without branching on `type`. Detecting a spoofing attempt is a `SUCCESS`: the service did its job.

        **Images.** JPG or PNG. The image is downscaled internally; no client-side resizing is needed. For best results send at least 1600 px on the longest side at JPEG quality 80 or better. The result is a liveness decision only; it does not verify identity — pair it with `matchFaces` for that.

        `INVALID_REQUEST` returns every problem found in `errors[]` at once (cumulative), so you can fix them in one pass.

        **`selfieAnalysis` reference.** Describes the evaluated face. Labels are derived from the face-analysis provider as follows:

        | Field | Values | Rule |
        |---|---|---|
        | `imageQuality` | `excellent` · `good` · `poor` | `excellent`: brightness ≥ 75 and sharpness ≥ 75 · `good`: both ≥ 50 · `poor`: otherwise. In practice `poor` almost always means a dark image, not an out-of-focus one. |
        | `detectionConfidence` | `high` · `medium` · `low` | `high` ≥ 95 · `medium` ≥ 80 · `low` below 80. |
        | `orientation` | `sideways` · `looking_left` · `looking_right` · `looking_up` · `looking_down` · `tilted` · `front` | Evaluated in that order, first match wins: `sideways` abs(yaw) ≥ 25° · `looking_left` yaw ≥ 10° · `looking_right` yaw ≤ −10° · `looking_up` pitch ≥ 20° · `looking_down` pitch ≤ −20° · `tilted` abs(roll) ≥ 15° · otherwise `front`. |
        | `eyesOpen`, `mouthOpen`, `wearingGlasses`, `wearingSunglasses`, `faceCovered` | `true` · `false` · `null` | `null` when the attribute could not be determined. `mouthOpen` is informational and never produces an issue. |

        `issues[]` lists every condition detected on the face. All possible values:

        | Value | Condition |
        |---|---|
        | `poor_image_quality` | `imageQuality` is `poor` |
        | `not_facing_camera` | `orientation` is not `front` |
        | `eyes_closed` | `eyesOpen` is `false` |
        | `face_covered` | `faceCovered` is `true` — mask, scarf, hand, hair over the eyes, face partly out of frame |
        | `wearing_glasses` | `wearingGlasses` is `true` — informational, not a capture problem |
        | `wearing_sunglasses` | `wearingSunglasses` is `true` |
        | `low_detection_confidence` | `detectionConfidence` is `low` |

        In production about 4 in 10 legitimate selfies carry at least one issue — treat `issues[]` as retry hints, not as rejection criteria.

        Parameters
        ----------
        selfie : str
            Selfie image of the subject in Base64 (PNG/JPG).

        allow_multiple_faces : typing.Optional[bool]
            Optional. When `false` (default), a selfie with another person in frame returns `MULTIPLE_FACES_DETECTED`. When `true`, the largest face in the image is evaluated and the others are ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CheckLivenessResponse]
            Liveness analysis result (Strict Envelope Pattern).
        """
        _response = self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/liveness-checks",
            method="POST",
            json={
                "selfie": selfie,
                "allowMultipleFaces": allow_multiple_faces,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CheckLivenessResponse,
                    parse_obj_as(
                        type_=CheckLivenessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawBiometricsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def match_faces(
        self,
        *,
        face: str,
        front: str,
        threshold: typing.Optional[int] = OMIT,
        document_type: typing.Optional[MatchFacesRequestDocumentType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MatchFacesResponse]:
        """
        **Credits:** 1 per call.

        Compares two facial images and returns a similarity score (0–100) plus a binary match/no-match decision. Typical use is 1:1 verification between a live selfie and the photograph on an ID document.

        Use this endpoint to confirm that the person presenting an ID is the same person depicted on it.

        Parameters
        ----------
        face : str
            Face image (selfie) in Base64 (PNG/JPG)

        front : str
            Front ID image in Base64 (PNG/JPG). Can be any official document globally.

        threshold : typing.Optional[int]
            Acceptance threshold (1-100). Default: **90** (KYC-grade). Lower (e.g. 80) is more permissive; higher is stricter. Overridable per request.

        document_type : typing.Optional[MatchFacesRequestDocumentType]
            Optional. Use a specific type (e.g. `INE`, `MEX_PASSPORT`) for strict validation against that exact document type. Use `ANY` to require the image be some recognized ID (auto-detected) — returns `NO_DOCUMENT_DETECTED` if not. Omit it to skip document validation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MatchFacesResponse]
            Biometric analysis result (Strict Envelope Pattern).
        """
        _response = await self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/face-matches",
            method="POST",
            json={
                "face": face,
                "front": front,
                "threshold": threshold,
                "documentType": document_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MatchFacesResponse,
                    parse_obj_as(
                        type_=MatchFacesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def check_liveness(
        self,
        *,
        selfie: str,
        allow_multiple_faces: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CheckLivenessResponse]:
        """
        **Credits:** 1 per call.

        Determines whether a selfie shows a real, live person in front of the camera (`isLive: true`) or a spoofing attempt (`isLive: false`).

        Returns:

        - **`isLive`**: the decision. `livenessScore` (0–100) is the fused output of the anti-spoofing models; the decision threshold is **62**.
        - **`confidence`**: how far the score landed from the threshold — `HIGH` (25 points or more), `MEDIUM` (10 or more) or `LOW`.
        - **`selfieAnalysis`**: quality and attribute labels of the evaluated face (image quality, orientation, eyes open, glasses, face covered, actionable `issues[]`). Same object as `matchFaces`, so both endpoints share one integration.

        **Multiple people in frame.** By default a selfie with another person present returns `MULTIPLE_FACES_DETECTED`. Send `allowMultipleFaces: true` to evaluate the largest face in the image instead (the person holding the phone); `selfieAnalysis` describes that same face. Only faces of at least 25% of the main face's area count as another person — people in the background do not.

        **Decision rule.** Accept only `type: SUCCESS` with `isLive: true`. `NO_FACE_DETECTED`, `MULTIPLE_FACES_DETECTED` and `IMAGE_UNREADABLE` also return `isLive: false`, but nothing was evaluated — `data` always carries the full object so you can read `data.isLive` without branching on `type`. Detecting a spoofing attempt is a `SUCCESS`: the service did its job.

        **Images.** JPG or PNG. The image is downscaled internally; no client-side resizing is needed. For best results send at least 1600 px on the longest side at JPEG quality 80 or better. The result is a liveness decision only; it does not verify identity — pair it with `matchFaces` for that.

        `INVALID_REQUEST` returns every problem found in `errors[]` at once (cumulative), so you can fix them in one pass.

        **`selfieAnalysis` reference.** Describes the evaluated face. Labels are derived from the face-analysis provider as follows:

        | Field | Values | Rule |
        |---|---|---|
        | `imageQuality` | `excellent` · `good` · `poor` | `excellent`: brightness ≥ 75 and sharpness ≥ 75 · `good`: both ≥ 50 · `poor`: otherwise. In practice `poor` almost always means a dark image, not an out-of-focus one. |
        | `detectionConfidence` | `high` · `medium` · `low` | `high` ≥ 95 · `medium` ≥ 80 · `low` below 80. |
        | `orientation` | `sideways` · `looking_left` · `looking_right` · `looking_up` · `looking_down` · `tilted` · `front` | Evaluated in that order, first match wins: `sideways` abs(yaw) ≥ 25° · `looking_left` yaw ≥ 10° · `looking_right` yaw ≤ −10° · `looking_up` pitch ≥ 20° · `looking_down` pitch ≤ −20° · `tilted` abs(roll) ≥ 15° · otherwise `front`. |
        | `eyesOpen`, `mouthOpen`, `wearingGlasses`, `wearingSunglasses`, `faceCovered` | `true` · `false` · `null` | `null` when the attribute could not be determined. `mouthOpen` is informational and never produces an issue. |

        `issues[]` lists every condition detected on the face. All possible values:

        | Value | Condition |
        |---|---|
        | `poor_image_quality` | `imageQuality` is `poor` |
        | `not_facing_camera` | `orientation` is not `front` |
        | `eyes_closed` | `eyesOpen` is `false` |
        | `face_covered` | `faceCovered` is `true` — mask, scarf, hand, hair over the eyes, face partly out of frame |
        | `wearing_glasses` | `wearingGlasses` is `true` — informational, not a capture problem |
        | `wearing_sunglasses` | `wearingSunglasses` is `true` |
        | `low_detection_confidence` | `detectionConfidence` is `low` |

        In production about 4 in 10 legitimate selfies carry at least one issue — treat `issues[]` as retry hints, not as rejection criteria.

        Parameters
        ----------
        selfie : str
            Selfie image of the subject in Base64 (PNG/JPG).

        allow_multiple_faces : typing.Optional[bool]
            Optional. When `false` (default), a selfie with another person in frame returns `MULTIPLE_FACES_DETECTED`. When `true`, the largest face in the image is evaluated and the others are ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CheckLivenessResponse]
            Liveness analysis result (Strict Envelope Pattern).
        """
        _response = await self._client_wrapper.httpx_client.request(
            "global/biometrics/v1/liveness-checks",
            method="POST",
            json={
                "selfie": selfie,
                "allowMultipleFaces": allow_multiple_faces,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CheckLivenessResponse,
                    parse_obj_as(
                        type_=CheckLivenessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
