# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.envelope import Envelope
from .raw_client import AsyncRawSocialSecurityClient, RawSocialSecurityClient
from .types.get_isste_record_response import GetIssteRecordResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SocialSecurityClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSocialSecurityClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSocialSecurityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSocialSecurityClient
        """
        return self._raw_client

    def lookup_imss_nss(self, *, curp: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Retrieves a worker's NSS (Número de Seguridad Social) from IMSS based on CURP. Returns the 11-digit NSS.

        Use this endpoint when onboarding employees for payroll or social-security registration: a CURP is far easier to collect than asking the candidate for their NSS card, which is frequently misplaced.

        Parameters
        ----------
        curp : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.social_security.lookup_imss_nss(
            curp="ALMR900805HDFRZA09",
        )
        """
        _response = self._raw_client.lookup_imss_nss(curp=curp, request_options=request_options)
        return _response.data

    def get_imss_employment_status(
        self, *, curp: str, nss: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Returns the current IMSS employment status of a worker (identified by CURP + NSS): whether they are currently registered as employed, inactive (no current registration), the modality of registration, the registered employer's RFC, employer name, state, base salary, contributed days, and the period the IMSS report covers.

        Use this endpoint for income verification (lending, leasing), employment confirmation (background checks), or to detect overlapping employment when complying with employment regulations.

        Parameters
        ----------
        curp : str

        nss : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.social_security.get_imss_employment_status(
            curp="GARM900101HDFRZA01",
            nss="92038109713",
        )
        """
        _response = self._raw_client.get_imss_employment_status(curp=curp, nss=nss, request_options=request_options)
        return _response.data

    def get_isste_record(
        self, *, curp: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIssteRecordResponse:
        """
        **Credits:** 1 per call.

        Retrieves a government worker's full ISSSTE record by CURP — personal data, affiliation, pension regime, positions, contribution history, address, assigned clinic, and the official PDF (always included as base64 in `data.files[]` (kind `document`)).

        A retrieved record returns `type: SUCCESS` for an active worker. `PENSIONER`, `SCHOLAR`, `INACTIVE`, and `DECEASED` flag KYC-material standings; when more than one applies, precedence is `DECEASED` > `PENSIONER`/`SCHOLAR` > `INACTIVE`. The raw affiliation status and beneficiary type are always in `data.affiliation`, so new statuses ISSSTE may report never break the contract. `CURP_NOT_FOUND` when the CURP has no ISSSTE record. Dates are ISO `YYYY-MM-DD`; monetary amounts are strings (MXN).

        **Field presence:** every field is always present (stable contract) — absent values are `null` (objects/scalars, including empty source strings normalized to `null`) or `[]` (arrays), never omitted. Examples: `pensions` and `family` are `[]` when the worker has none; `terminationDate` and a history row's `endDate` are `null` while ongoing; binary assets in `data.files[]` follow array semantics — only assets actually produced are listed (absent ones omitted, not `null`). Unmigrated placeholder values from ISSSTE (e.g. address `POR ACTUALIZAR`, clinic `FAVOR DE ATENDER A ESTE TRABAJADOR` / clave `0409999`, state `ENTIDAD DESCONOCIDA`) are normalized to `null` (data not yet migrated). ISSSTE only exposes records for titulares (TRABAJADOR/PENSIONISTA/BECARIO); a CURP that is only a dependant (not a titular) returns `CURP_NOT_FOUND`. To retrieve a dependant, query the titular CURP and match `data.family[]` by the dependant CURP. `beneficiaryType` is derived authoritatively from the record (a DIRECT pension means PENSIONISTA even if the document labels them TRABAJADOR); each pension carries a derived `category` (DIRECT/SURVIVOR/INSURANCE/DISABILITY).

        Parameters
        ----------
        curp : str
            CURP of the government worker whose ISSSTE record is requested.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIssteRecordResponse
            ISSSTE record result (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.social_security.get_isste_record(
            curp="GOTM850312MDFMRX05",
        )
        """
        _response = self._raw_client.get_isste_record(curp=curp, request_options=request_options)
        return _response.data


class AsyncSocialSecurityClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSocialSecurityClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSocialSecurityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSocialSecurityClient
        """
        return self._raw_client

    async def lookup_imss_nss(self, *, curp: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Retrieves a worker's NSS (Número de Seguridad Social) from IMSS based on CURP. Returns the 11-digit NSS.

        Use this endpoint when onboarding employees for payroll or social-security registration: a CURP is far easier to collect than asking the candidate for their NSS card, which is frequently misplaced.

        Parameters
        ----------
        curp : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_security.lookup_imss_nss(
                curp="ALMR900805HDFRZA09",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup_imss_nss(curp=curp, request_options=request_options)
        return _response.data

    async def get_imss_employment_status(
        self, *, curp: str, nss: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Returns the current IMSS employment status of a worker (identified by CURP + NSS): whether they are currently registered as employed, inactive (no current registration), the modality of registration, the registered employer's RFC, employer name, state, base salary, contributed days, and the period the IMSS report covers.

        Use this endpoint for income verification (lending, leasing), employment confirmation (background checks), or to detect overlapping employment when complying with employment regulations.

        Parameters
        ----------
        curp : str

        nss : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_security.get_imss_employment_status(
                curp="GARM900101HDFRZA01",
                nss="92038109713",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_imss_employment_status(
            curp=curp, nss=nss, request_options=request_options
        )
        return _response.data

    async def get_isste_record(
        self, *, curp: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIssteRecordResponse:
        """
        **Credits:** 1 per call.

        Retrieves a government worker's full ISSSTE record by CURP — personal data, affiliation, pension regime, positions, contribution history, address, assigned clinic, and the official PDF (always included as base64 in `data.files[]` (kind `document`)).

        A retrieved record returns `type: SUCCESS` for an active worker. `PENSIONER`, `SCHOLAR`, `INACTIVE`, and `DECEASED` flag KYC-material standings; when more than one applies, precedence is `DECEASED` > `PENSIONER`/`SCHOLAR` > `INACTIVE`. The raw affiliation status and beneficiary type are always in `data.affiliation`, so new statuses ISSSTE may report never break the contract. `CURP_NOT_FOUND` when the CURP has no ISSSTE record. Dates are ISO `YYYY-MM-DD`; monetary amounts are strings (MXN).

        **Field presence:** every field is always present (stable contract) — absent values are `null` (objects/scalars, including empty source strings normalized to `null`) or `[]` (arrays), never omitted. Examples: `pensions` and `family` are `[]` when the worker has none; `terminationDate` and a history row's `endDate` are `null` while ongoing; binary assets in `data.files[]` follow array semantics — only assets actually produced are listed (absent ones omitted, not `null`). Unmigrated placeholder values from ISSSTE (e.g. address `POR ACTUALIZAR`, clinic `FAVOR DE ATENDER A ESTE TRABAJADOR` / clave `0409999`, state `ENTIDAD DESCONOCIDA`) are normalized to `null` (data not yet migrated). ISSSTE only exposes records for titulares (TRABAJADOR/PENSIONISTA/BECARIO); a CURP that is only a dependant (not a titular) returns `CURP_NOT_FOUND`. To retrieve a dependant, query the titular CURP and match `data.family[]` by the dependant CURP. `beneficiaryType` is derived authoritatively from the record (a DIRECT pension means PENSIONISTA even if the document labels them TRABAJADOR); each pension carries a derived `category` (DIRECT/SURVIVOR/INSURANCE/DISABILITY).

        Parameters
        ----------
        curp : str
            CURP of the government worker whose ISSSTE record is requested.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIssteRecordResponse
            ISSSTE record result (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.social_security.get_isste_record(
                curp="GOTM850312MDFMRX05",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_isste_record(curp=curp, request_options=request_options)
        return _response.data
