# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.envelope import Envelope
from .raw_client import AsyncRawRenapoClient, RawRenapoClient
from .types.lookup_curp_request_gender import LookupCurpRequestGender

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RenapoClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRenapoClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRenapoClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRenapoClient
        """
        return self._raw_client

    def validate_curp(
        self,
        *,
        curp: str,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates a CURP (Clave Única de Registro de Población) against the official RENAPO registry and returns the full personal record associated with it: given names, surnames, gender, date of birth, birth state, document status (active, deceased, apocryphal, judicial suspension), and registration metadata.

        Optionally generates the associated 13-character RFC (Registro Federal de Contribuyentes) when `generateRfc: true` is sent. RFC generation is deterministic from CURP and does not call SAT.

        Use this endpoint when you have a CURP and need to confirm it is genuine, find out who owns it, or detect if the holder is deceased before extending a financial product.

        Parameters
        ----------
        curp : str
            CURP to validate (18 characters).

        generate_rfc : typing.Optional[bool]
            Generate RFC associated with the CURP.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.renapo.validate_curp(
            curp="TEST900101HDFRRN09",
        )
        """
        _response = self._raw_client.validate_curp(
            curp=curp, generate_rfc=generate_rfc, request_options=request_options
        )
        return _response.data

    def lookup_curp(
        self,
        *,
        given_names: str,
        first_surname: str,
        date_of_birth: str,
        gender: LookupCurpRequestGender,
        birth_state_code: str,
        second_surname: typing.Optional[str] = OMIT,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 2 per call.

        Reconstructs a CURP from the four official input fields: given names, first surname, second surname, gender, date of birth, and birth state code. Calls RENAPO and returns the matching CURP plus the full personal record (same shape as `validateCurp`).

        Use this endpoint when your KYC form collects names and date of birth but not the CURP, and you need the CURP to file a financial product or report to regulators. The lookup uses RENAPO's strict matching — if any field is misspelled, no match is returned (`CURP_NOT_FOUND`).

        Parameters
        ----------
        given_names : str

        first_surname : str

        date_of_birth : str
            Format YYYY-MM-DD

        gender : LookupCurpRequestGender

        birth_state_code : str

        second_surname : typing.Optional[str]

        generate_rfc : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.renapo.lookup_curp(
            given_names="JUAN",
            first_surname="PEREZ",
            date_of_birth="1990-01-01",
            gender="H",
            birth_state_code="DF",
        )
        """
        _response = self._raw_client.lookup_curp(
            given_names=given_names,
            first_surname=first_surname,
            date_of_birth=date_of_birth,
            gender=gender,
            birth_state_code=birth_state_code,
            second_surname=second_surname,
            generate_rfc=generate_rfc,
            request_options=request_options,
        )
        return _response.data

    def extract_curp_document(
        self,
        *,
        curp: str,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 2 per call.

        Retrieves the official RENAPO CURP document ("Constancia de la CURP") as a PDF, together with the full validated record and the CURP's RENAPO status — the **same status matrix as `curp-validations`** (active, homonymy, deceased, apocryphal, judicial suspension, inactive). Use it when you need the citizen's official, printable certificate, not just the validated data.

        The PDF is returned **inline as base64** in `data.document.content`, alongside the parsed identity fields. This is a **synchronous** call.

        Optionally pass `generateRfc: true` to also receive the deterministic `personalInfo.rfc` (computed from the CURP, no SAT call) — identical to `curp-validations`.

        **Why it differs from `curp-validations`:** this endpoint retrieves the actual document from RENAPO, so a response takes a little longer to return. It is priced at **2 credits** and has a lower rate limit than the high-volume `curp-validations`.

        Parameters
        ----------
        curp : str
            The 18-character CURP whose official document is requested.

        generate_rfc : typing.Optional[bool]
            Generate the RFC associated with the CURP. Deterministic from the CURP (no SAT call). When true, `personalInfo.rfc` is included — same as `curp-validations`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            CURP document result (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.renapo.extract_curp_document(
            curp="TEST900101HDFRRN09",
        )
        """
        _response = self._raw_client.extract_curp_document(
            curp=curp, generate_rfc=generate_rfc, request_options=request_options
        )
        return _response.data


class AsyncRenapoClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRenapoClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRenapoClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRenapoClient
        """
        return self._raw_client

    async def validate_curp(
        self,
        *,
        curp: str,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates a CURP (Clave Única de Registro de Población) against the official RENAPO registry and returns the full personal record associated with it: given names, surnames, gender, date of birth, birth state, document status (active, deceased, apocryphal, judicial suspension), and registration metadata.

        Optionally generates the associated 13-character RFC (Registro Federal de Contribuyentes) when `generateRfc: true` is sent. RFC generation is deterministic from CURP and does not call SAT.

        Use this endpoint when you have a CURP and need to confirm it is genuine, find out who owns it, or detect if the holder is deceased before extending a financial product.

        Parameters
        ----------
        curp : str
            CURP to validate (18 characters).

        generate_rfc : typing.Optional[bool]
            Generate RFC associated with the CURP.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.renapo.validate_curp(
                curp="TEST900101HDFRRN09",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_curp(
            curp=curp, generate_rfc=generate_rfc, request_options=request_options
        )
        return _response.data

    async def lookup_curp(
        self,
        *,
        given_names: str,
        first_surname: str,
        date_of_birth: str,
        gender: LookupCurpRequestGender,
        birth_state_code: str,
        second_surname: typing.Optional[str] = OMIT,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 2 per call.

        Reconstructs a CURP from the four official input fields: given names, first surname, second surname, gender, date of birth, and birth state code. Calls RENAPO and returns the matching CURP plus the full personal record (same shape as `validateCurp`).

        Use this endpoint when your KYC form collects names and date of birth but not the CURP, and you need the CURP to file a financial product or report to regulators. The lookup uses RENAPO's strict matching — if any field is misspelled, no match is returned (`CURP_NOT_FOUND`).

        Parameters
        ----------
        given_names : str

        first_surname : str

        date_of_birth : str
            Format YYYY-MM-DD

        gender : LookupCurpRequestGender

        birth_state_code : str

        second_surname : typing.Optional[str]

        generate_rfc : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.renapo.lookup_curp(
                given_names="JUAN",
                first_surname="PEREZ",
                date_of_birth="1990-01-01",
                gender="H",
                birth_state_code="DF",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup_curp(
            given_names=given_names,
            first_surname=first_surname,
            date_of_birth=date_of_birth,
            gender=gender,
            birth_state_code=birth_state_code,
            second_surname=second_surname,
            generate_rfc=generate_rfc,
            request_options=request_options,
        )
        return _response.data

    async def extract_curp_document(
        self,
        *,
        curp: str,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 2 per call.

        Retrieves the official RENAPO CURP document ("Constancia de la CURP") as a PDF, together with the full validated record and the CURP's RENAPO status — the **same status matrix as `curp-validations`** (active, homonymy, deceased, apocryphal, judicial suspension, inactive). Use it when you need the citizen's official, printable certificate, not just the validated data.

        The PDF is returned **inline as base64** in `data.document.content`, alongside the parsed identity fields. This is a **synchronous** call.

        Optionally pass `generateRfc: true` to also receive the deterministic `personalInfo.rfc` (computed from the CURP, no SAT call) — identical to `curp-validations`.

        **Why it differs from `curp-validations`:** this endpoint retrieves the actual document from RENAPO, so a response takes a little longer to return. It is priced at **2 credits** and has a lower rate limit than the high-volume `curp-validations`.

        Parameters
        ----------
        curp : str
            The 18-character CURP whose official document is requested.

        generate_rfc : typing.Optional[bool]
            Generate the RFC associated with the CURP. Deterministic from the CURP (no SAT call). When true, `personalInfo.rfc` is included — same as `curp-validations`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            CURP document result (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.renapo.extract_curp_document(
                curp="TEST900101HDFRRN09",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.extract_curp_document(
            curp=curp, generate_rfc=generate_rfc, request_options=request_options
        )
        return _response.data
