# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.envelope import Envelope
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.too_many_requests_error import TooManyRequestsError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .types.lookup_curp_request_gender import LookupCurpRequestGender
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RenapoClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def validate_curp(
        self,
        *,
        curp: str,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates a CURP (Clave Única de Registro de Población) against the official RENAPO registry and returns the full personal record associated with it: given names, surnames, gender, date of birth, birth state, document status (active, deceased, apocryphal, judicial suspension), and registration metadata.

        Optionally generates the associated 13-character RFC (Registro Federal de Contribuyentes) when `generateRfc: true` is sent. RFC generation is deterministic from CURP and does not call SAT.

        Use this endpoint when you have a CURP and need to confirm it is genuine, find out who owns it, or detect if the holder is deceased before extending a financial product.

        Parameters
        ----------
        curp : str
            CURP to validate (18 characters).

        generate_rfc : typing.Optional[bool]
            Generate RFC associated with the CURP.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.renapo.validate_curp(
            curp="TEST900101HDFRRN09",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "mex/renapo/v1/curp-validations",
            method="POST",
            json={
                "curp": curp,
                "generateRfc": generate_rfc,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def lookup_curp(
        self,
        *,
        given_names: str,
        first_surname: str,
        date_of_birth: str,
        gender: LookupCurpRequestGender,
        birth_state_code: str,
        second_surname: typing.Optional[str] = OMIT,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 2 per call.

        Reconstructs a CURP from the four official input fields: given names, first surname, second surname, gender, date of birth, and birth state code. Calls RENAPO and returns the matching CURP plus the full personal record (same shape as `validateCurp`).

        Use this endpoint when your KYC form collects names and date of birth but not the CURP, and you need the CURP to file a financial product or report to regulators. The lookup uses RENAPO's strict matching — if any field is misspelled, no match is returned (`CURP_NOT_FOUND`).

        Parameters
        ----------
        given_names : str

        first_surname : str

        date_of_birth : str
            Format YYYY-MM-DD

        gender : LookupCurpRequestGender

        birth_state_code : str

        second_surname : typing.Optional[str]

        generate_rfc : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.renapo.lookup_curp(
            given_names="JUAN",
            first_surname="PEREZ",
            date_of_birth="1990-01-01",
            gender="H",
            birth_state_code="DF",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "mex/renapo/v1/curp-lookups",
            method="POST",
            json={
                "givenNames": given_names,
                "firstSurname": first_surname,
                "secondSurname": second_surname,
                "dateOfBirth": date_of_birth,
                "gender": gender,
                "birthStateCode": birth_state_code,
                "generateRfc": generate_rfc,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncRenapoClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def validate_curp(
        self,
        *,
        curp: str,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates a CURP (Clave Única de Registro de Población) against the official RENAPO registry and returns the full personal record associated with it: given names, surnames, gender, date of birth, birth state, document status (active, deceased, apocryphal, judicial suspension), and registration metadata.

        Optionally generates the associated 13-character RFC (Registro Federal de Contribuyentes) when `generateRfc: true` is sent. RFC generation is deterministic from CURP and does not call SAT.

        Use this endpoint when you have a CURP and need to confirm it is genuine, find out who owns it, or detect if the holder is deceased before extending a financial product.

        Parameters
        ----------
        curp : str
            CURP to validate (18 characters).

        generate_rfc : typing.Optional[bool]
            Generate RFC associated with the CURP.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.renapo.validate_curp(
                curp="TEST900101HDFRRN09",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "mex/renapo/v1/curp-validations",
            method="POST",
            json={
                "curp": curp,
                "generateRfc": generate_rfc,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def lookup_curp(
        self,
        *,
        given_names: str,
        first_surname: str,
        date_of_birth: str,
        gender: LookupCurpRequestGender,
        birth_state_code: str,
        second_surname: typing.Optional[str] = OMIT,
        generate_rfc: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Envelope:
        """
        **Credits:** 2 per call.

        Reconstructs a CURP from the four official input fields: given names, first surname, second surname, gender, date of birth, and birth state code. Calls RENAPO and returns the matching CURP plus the full personal record (same shape as `validateCurp`).

        Use this endpoint when your KYC form collects names and date of birth but not the CURP, and you need the CURP to file a financial product or report to regulators. The lookup uses RENAPO's strict matching — if any field is misspelled, no match is returned (`CURP_NOT_FOUND`).

        Parameters
        ----------
        given_names : str

        first_surname : str

        date_of_birth : str
            Format YYYY-MM-DD

        gender : LookupCurpRequestGender

        birth_state_code : str

        second_surname : typing.Optional[str]

        generate_rfc : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Business Responses (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.renapo.lookup_curp(
                given_names="JUAN",
                first_surname="PEREZ",
                date_of_birth="1990-01-01",
                gender="H",
                birth_state_code="DF",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "mex/renapo/v1/curp-lookups",
            method="POST",
            json={
                "givenNames": given_names,
                "firstSurname": first_surname,
                "secondSurname": second_surname,
                "dateOfBirth": date_of_birth,
                "gender": gender,
                "birthStateCode": birth_state_code,
                "generateRfc": generate_rfc,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Envelope,
                    parse_obj_as(
                        type_=Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    typing.cast(
                        Envelope,
                        parse_obj_as(
                            type_=Envelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
