# This file was auto-generated by Fern from our API Definition.

import typing

MatchFacesRequestDocumentType = typing.Union[
    typing.Literal["IFE", "INE", "MEX_PASSPORT", "MEX_RESIDENCE_CARD", "MEX_PROFESSIONAL_ID", "ANY"], typing.Any
]
