# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.envelope import Envelope
from .raw_client import AsyncRawFiscalClient, RawFiscalClient
from .types.extract_csf_request import ExtractCsfRequest
from .types.validate_cfdi_request import ValidateCfdiRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FiscalClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFiscalClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFiscalClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFiscalClient
        """
        return self._raw_client

    def validate_rfc(self, *, rfc: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates the structure and current status of a Mexican RFC (Registro Federal de Contribuyentes) against the SAT registry. Returns the taxpayer type (individual or legal entity), registration status, and the official SAT message.

        Use this endpoint to confirm that the RFC your customer provided is real, well-formed, and currently active with SAT before extending credit, issuing invoices, or signing contracts.

        **Risk Level Matrix (`riskLevel`):**
        - `NONE` (envelope `type: SUCCESS`): RFC exists in the SAT padrón and is authorized to issue / receive invoices (`isBillable: true`). Safe for automated approval.
        - `LOW` (envelope `type: RFC_NOT_INVOICEABLE`): RFC exists in the SAT padrón but is **restricted** for invoicing — typically a legal entity that has not completed its fiscal-status onboarding or has been suspended. The taxpayer is real, just not currently invoiceable.
        - `CRITICAL` (envelope `type: RFC_NOT_FOUND`): RFC is **not registered** in the SAT padrón. Either it was never issued, or the value provided is a typo or fabricated. Do not extend credit, issue invoices, or accept as a counterparty without further verification.

        `MEDIUM` and `HIGH` are not produced by this endpoint — the SAT padrón only distinguishes the three outcomes above.

        Parameters
        ----------
        rfc : str
            Taxpayer's RFC (12 or 13 characters).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            RFC Validation Result (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.fiscal.validate_rfc(
            rfc="GARM900101HDF",
        )
        """
        _response = self._raw_client.validate_rfc(rfc=rfc, request_options=request_options)
        return _response.data

    def extract_csf(
        self, *, request: ExtractCsfRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Extracts structured data from a Constancia de Situación Fiscal (CSF) — the official PDF document issued by SAT that proves a taxpayer's fiscal situation. You can submit the CSF as a base64-encoded file (PDF/PNG/JPG) and get back the full content as JSON, or alternatively pass RFC + CIF (the tax-certificate code) to retrieve the same data directly from SAT's public QR validator.

        Returns the legal name, address, fiscal regime, economic activities, registration date, and tax obligations. Use this endpoint to automate vendor onboarding and to keep your records of partners' fiscal data continuously up to date.

        Parameters
        ----------
        request : ExtractCsfRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            All responses are returned with HTTP 200. The JSON payload defines the success or failure of the transaction.

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.fiscal.extract_csf(
            request={"rfc": "PELJ900101AAA", "cif": "24010199999"},
        )
        """
        _response = self._raw_client.extract_csf(request=request, request_options=request_options)
        return _response.data

    def validate_cfdi(
        self, *, request: ValidateCfdiRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates a CFDI (Comprobante Fiscal Digital por Internet) — Mexico's mandatory electronic invoice — by checking its current status with SAT. Returns whether the CFDI is currently valid (`VALID`) or cancelled (`CANCELED`), the cancellation status (e.g. requires receiver acceptance), and the fiscal effect (`INCOME`, `EXPENSE`, `TRANSPORT`, `PAYROLL`, `PAYMENT`).

        Use this endpoint when reconciling supplier invoices, processing expense reports, or ensuring that the invoices you receive are real and not later cancelled by the issuer without your knowledge.

        Parameters
        ----------
        request : ValidateCfdiRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            CFDI Validation Result (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.fiscal.validate_cfdi(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.validate_cfdi(request=request, request_options=request_options)
        return _response.data


class AsyncFiscalClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFiscalClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFiscalClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFiscalClient
        """
        return self._raw_client

    async def validate_rfc(self, *, rfc: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates the structure and current status of a Mexican RFC (Registro Federal de Contribuyentes) against the SAT registry. Returns the taxpayer type (individual or legal entity), registration status, and the official SAT message.

        Use this endpoint to confirm that the RFC your customer provided is real, well-formed, and currently active with SAT before extending credit, issuing invoices, or signing contracts.

        **Risk Level Matrix (`riskLevel`):**
        - `NONE` (envelope `type: SUCCESS`): RFC exists in the SAT padrón and is authorized to issue / receive invoices (`isBillable: true`). Safe for automated approval.
        - `LOW` (envelope `type: RFC_NOT_INVOICEABLE`): RFC exists in the SAT padrón but is **restricted** for invoicing — typically a legal entity that has not completed its fiscal-status onboarding or has been suspended. The taxpayer is real, just not currently invoiceable.
        - `CRITICAL` (envelope `type: RFC_NOT_FOUND`): RFC is **not registered** in the SAT padrón. Either it was never issued, or the value provided is a typo or fabricated. Do not extend credit, issue invoices, or accept as a counterparty without further verification.

        `MEDIUM` and `HIGH` are not produced by this endpoint — the SAT padrón only distinguishes the three outcomes above.

        Parameters
        ----------
        rfc : str
            Taxpayer's RFC (12 or 13 characters).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            RFC Validation Result (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fiscal.validate_rfc(
                rfc="GARM900101HDF",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_rfc(rfc=rfc, request_options=request_options)
        return _response.data

    async def extract_csf(
        self, *, request: ExtractCsfRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Extracts structured data from a Constancia de Situación Fiscal (CSF) — the official PDF document issued by SAT that proves a taxpayer's fiscal situation. You can submit the CSF as a base64-encoded file (PDF/PNG/JPG) and get back the full content as JSON, or alternatively pass RFC + CIF (the tax-certificate code) to retrieve the same data directly from SAT's public QR validator.

        Returns the legal name, address, fiscal regime, economic activities, registration date, and tax obligations. Use this endpoint to automate vendor onboarding and to keep your records of partners' fiscal data continuously up to date.

        Parameters
        ----------
        request : ExtractCsfRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            All responses are returned with HTTP 200. The JSON payload defines the success or failure of the transaction.

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fiscal.extract_csf(
                request={"rfc": "PELJ900101AAA", "cif": "24010199999"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.extract_csf(request=request, request_options=request_options)
        return _response.data

    async def validate_cfdi(
        self, *, request: ValidateCfdiRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates a CFDI (Comprobante Fiscal Digital por Internet) — Mexico's mandatory electronic invoice — by checking its current status with SAT. Returns whether the CFDI is currently valid (`VALID`) or cancelled (`CANCELED`), the cancellation status (e.g. requires receiver acceptance), and the fiscal effect (`INCOME`, `EXPENSE`, `TRANSPORT`, `PAYROLL`, `PAYMENT`).

        Use this endpoint when reconciling supplier invoices, processing expense reports, or ensuring that the invoices you receive are real and not later cancelled by the issuer without your knowledge.

        Parameters
        ----------
        request : ValidateCfdiRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            CFDI Validation Result (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fiscal.validate_cfdi(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_cfdi(request=request, request_options=request_options)
        return _response.data
