# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.envelope import Envelope
from .raw_client import AsyncRawProofOfAddressClient, RawProofOfAddressClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProofOfAddressClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProofOfAddressClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProofOfAddressClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProofOfAddressClient
        """
        return self._raw_client

    def extract_proof_of_address(
        self, *, file: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Performs OCR on a Mexican proof-of-address document — utility bills (water, electricity, gas, internet, telephone) and bank statements — and returns the structured data printed on it.

        Returns:

        - **`provider`**: the issuing utility or institution (CFE, Telmex, Agua, etc.), so you can apply provider-specific business rules and recognize legitimate document layouts.
        - **`personalInfo`**: holder name as printed on the document.
        - **`address`**: full address as printed (street, exterior / interior number, neighborhood, municipality, state, postal code).
        - **`billing`**: issuance date, account number, period covered.
        - **`validations`**: flags about document age, document type detection confidence, and structural consistency checks.

        Use this endpoint to automate address verification in KYC flows. The extracted address can be cross-checked against the address your customer submitted at signup.

        Parameters
        ----------
        file : str
            Proof of Address file in Base64 (PNG, JPG, or PDF).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Extraction results (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.proof_of_address.extract_proof_of_address(
            file="file",
        )
        """
        _response = self._raw_client.extract_proof_of_address(file=file, request_options=request_options)
        return _response.data


class AsyncProofOfAddressClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProofOfAddressClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProofOfAddressClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProofOfAddressClient
        """
        return self._raw_client

    async def extract_proof_of_address(
        self, *, file: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Envelope:
        """
        **Credits:** 1 per call.

        Performs OCR on a Mexican proof-of-address document — utility bills (water, electricity, gas, internet, telephone) and bank statements — and returns the structured data printed on it.

        Returns:

        - **`provider`**: the issuing utility or institution (CFE, Telmex, Agua, etc.), so you can apply provider-specific business rules and recognize legitimate document layouts.
        - **`personalInfo`**: holder name as printed on the document.
        - **`address`**: full address as printed (street, exterior / interior number, neighborhood, municipality, state, postal code).
        - **`billing`**: issuance date, account number, period covered.
        - **`validations`**: flags about document age, document type detection confidence, and structural consistency checks.

        Use this endpoint to automate address verification in KYC flows. The extracted address can be cross-checked against the address your customer submitted at signup.

        Parameters
        ----------
        file : str
            Proof of Address file in Base64 (PNG, JPG, or PDF).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Extraction results (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.proof_of_address.extract_proof_of_address(
                file="file",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.extract_proof_of_address(file=file, request_options=request_options)
        return _response.data
