# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawBankingClient, RawBankingClient
from .types.validate_cep_request import ValidateCepRequest
from .types.validate_cep_response import ValidateCepResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BankingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBankingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBankingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBankingClient
        """
        return self._raw_client

    def validate_cep(
        self, *, request: ValidateCepRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ValidateCepResponse:
        """
        **Credits:** 1 per call.

        Validates a Mexican SPEI transfer against Banco de México's official **CEP** service ("Comprobante Electrónico de Pago") and returns the verified transfer details together with Banxico's cryptographic proof. Use it to confirm that a SPEI payment actually settled, for reconciliation, payout confirmation, or fraud checks on a claimed transfer.

        Parameters
        ----------
        request : ValidateCepRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidateCepResponse
            CEP validation result (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.banking.validate_cep(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.validate_cep(request=request, request_options=request_options)
        return _response.data


class AsyncBankingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBankingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBankingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBankingClient
        """
        return self._raw_client

    async def validate_cep(
        self, *, request: ValidateCepRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ValidateCepResponse:
        """
        **Credits:** 1 per call.

        Validates a Mexican SPEI transfer against Banco de México's official **CEP** service ("Comprobante Electrónico de Pago") and returns the verified transfer details together with Banxico's cryptographic proof. Use it to confirm that a SPEI payment actually settled, for reconciliation, payout confirmation, or fraud checks on a claimed transfer.

        Parameters
        ----------
        request : ValidateCepRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidateCepResponse
            CEP validation result (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.banking.validate_cep(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_cep(request=request, request_options=request_options)
        return _response.data
