# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.envelope import Envelope
from .raw_client import AsyncRawEmailClient, RawEmailClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EmailClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEmailClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEmailClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEmailClient
        """
        return self._raw_client

    def validate_email(self, *, email: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates an email address for deliverability and risk. Returns the normalized address, deliverability verdict (`deliverable`, `risky`, `undeliverable`), a quality score (0–100), a toxicity score, and a set of boolean verdicts (`isFree`, `isDisposable`, `isRoleAccount`, `isFull`, `isCatchAll`, `isToxic`).

        Use this endpoint at signup time to reject typos and disposable addresses before they enter your database, reducing bounce rates on transactional email and fraud signals from throwaway accounts.

        **`riskLevel` reference** — standardized scoring you can branch on:

        | Level | When |
        |---|---|
        | `NONE` | Mailbox is deliverable and not flagged as disposable or toxic. |
        | `MEDIUM` | Domain is catch-all — accepts every address, so the specific mailbox cannot be confirmed to exist. |
        | `HIGH` | Deliverability is `risky` or `unknown` (e.g. mail server rejects probes), OR the domain belongs to a disposable / temporary email provider (Mailinator, 10minutemail, Guerrillamail, etc.). |
        | `CRITICAL` | Mailbox is `undeliverable` (does not exist or is full), OR the address scores above 40 on the toxicity index (associated with spam / abuse). |

        The `verdicts` object always carries the underlying signals (`isFree`, `isDisposable`, `isRoleAccount`, `isFull`, `isCatchAll`, `isToxic`) so you can apply your own scoring on top if you need finer granularity.

        Parameters
        ----------
        email : str
            The email address to be validated.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Validation results (Strict Envelope Pattern).

        Examples
        --------
        from origoid import OrigoID

        client = OrigoID(
            api_key="YOUR_API_KEY",
        )
        client.email.validate_email(
            email="user@example.com",
        )
        """
        _response = self._raw_client.validate_email(email=email, request_options=request_options)
        return _response.data


class AsyncEmailClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEmailClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEmailClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEmailClient
        """
        return self._raw_client

    async def validate_email(self, *, email: str, request_options: typing.Optional[RequestOptions] = None) -> Envelope:
        """
        **Credits:** 1 per call.

        Validates an email address for deliverability and risk. Returns the normalized address, deliverability verdict (`deliverable`, `risky`, `undeliverable`), a quality score (0–100), a toxicity score, and a set of boolean verdicts (`isFree`, `isDisposable`, `isRoleAccount`, `isFull`, `isCatchAll`, `isToxic`).

        Use this endpoint at signup time to reject typos and disposable addresses before they enter your database, reducing bounce rates on transactional email and fraud signals from throwaway accounts.

        **`riskLevel` reference** — standardized scoring you can branch on:

        | Level | When |
        |---|---|
        | `NONE` | Mailbox is deliverable and not flagged as disposable or toxic. |
        | `MEDIUM` | Domain is catch-all — accepts every address, so the specific mailbox cannot be confirmed to exist. |
        | `HIGH` | Deliverability is `risky` or `unknown` (e.g. mail server rejects probes), OR the domain belongs to a disposable / temporary email provider (Mailinator, 10minutemail, Guerrillamail, etc.). |
        | `CRITICAL` | Mailbox is `undeliverable` (does not exist or is full), OR the address scores above 40 on the toxicity index (associated with spam / abuse). |

        The `verdicts` object always carries the underlying signals (`isFree`, `isDisposable`, `isRoleAccount`, `isFull`, `isCatchAll`, `isToxic`) so you can apply your own scoring on top if you need finer granularity.

        Parameters
        ----------
        email : str
            The email address to be validated.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Envelope
            Validation results (Strict Envelope Pattern).

        Examples
        --------
        import asyncio

        from origoid import AsyncOrigoID

        client = AsyncOrigoID(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.email.validate_email(
                email="user@example.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_email(email=email, request_options=request_options)
        return _response.data
