# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import OrigoIDEnvironment

if typing.TYPE_CHECKING:
    from .authentication.client import AsyncAuthenticationClient, AuthenticationClient
    from .banking.client import AsyncBankingClient, BankingClient
    from .biometrics.client import AsyncBiometricsClient, BiometricsClient
    from .compliance.client import AsyncComplianceClient, ComplianceClient
    from .email.client import AsyncEmailClient, EmailClient
    from .fiscal.client import AsyncFiscalClient, FiscalClient
    from .ine.client import AsyncIneClient, IneClient
    from .proof_of_address.client import AsyncProofOfAddressClient, ProofOfAddressClient
    from .renapo.client import AsyncRenapoClient, RenapoClient
    from .social_security.client import AsyncSocialSecurityClient, SocialSecurityClient


class OrigoID:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : OrigoIDEnvironment
        The environment to use for requests from the client. from .environment import OrigoIDEnvironment



        Defaults to OrigoIDEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from origoid import OrigoID

    client = OrigoID(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: OrigoIDEnvironment = OrigoIDEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._authentication: typing.Optional[AuthenticationClient] = None
        self._renapo: typing.Optional[RenapoClient] = None
        self._social_security: typing.Optional[SocialSecurityClient] = None
        self._ine: typing.Optional[IneClient] = None
        self._biometrics: typing.Optional[BiometricsClient] = None
        self._compliance: typing.Optional[ComplianceClient] = None
        self._email: typing.Optional[EmailClient] = None
        self._proof_of_address: typing.Optional[ProofOfAddressClient] = None
        self._fiscal: typing.Optional[FiscalClient] = None
        self._banking: typing.Optional[BankingClient] = None

    @property
    def authentication(self):
        if self._authentication is None:
            from .authentication.client import AuthenticationClient  # noqa: E402

            self._authentication = AuthenticationClient(client_wrapper=self._client_wrapper)
        return self._authentication

    @property
    def renapo(self):
        if self._renapo is None:
            from .renapo.client import RenapoClient  # noqa: E402

            self._renapo = RenapoClient(client_wrapper=self._client_wrapper)
        return self._renapo

    @property
    def social_security(self):
        if self._social_security is None:
            from .social_security.client import SocialSecurityClient  # noqa: E402

            self._social_security = SocialSecurityClient(client_wrapper=self._client_wrapper)
        return self._social_security

    @property
    def ine(self):
        if self._ine is None:
            from .ine.client import IneClient  # noqa: E402

            self._ine = IneClient(client_wrapper=self._client_wrapper)
        return self._ine

    @property
    def biometrics(self):
        if self._biometrics is None:
            from .biometrics.client import BiometricsClient  # noqa: E402

            self._biometrics = BiometricsClient(client_wrapper=self._client_wrapper)
        return self._biometrics

    @property
    def compliance(self):
        if self._compliance is None:
            from .compliance.client import ComplianceClient  # noqa: E402

            self._compliance = ComplianceClient(client_wrapper=self._client_wrapper)
        return self._compliance

    @property
    def email(self):
        if self._email is None:
            from .email.client import EmailClient  # noqa: E402

            self._email = EmailClient(client_wrapper=self._client_wrapper)
        return self._email

    @property
    def proof_of_address(self):
        if self._proof_of_address is None:
            from .proof_of_address.client import ProofOfAddressClient  # noqa: E402

            self._proof_of_address = ProofOfAddressClient(client_wrapper=self._client_wrapper)
        return self._proof_of_address

    @property
    def fiscal(self):
        if self._fiscal is None:
            from .fiscal.client import FiscalClient  # noqa: E402

            self._fiscal = FiscalClient(client_wrapper=self._client_wrapper)
        return self._fiscal

    @property
    def banking(self):
        if self._banking is None:
            from .banking.client import BankingClient  # noqa: E402

            self._banking = BankingClient(client_wrapper=self._client_wrapper)
        return self._banking


class AsyncOrigoID:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : OrigoIDEnvironment
        The environment to use for requests from the client. from .environment import OrigoIDEnvironment



        Defaults to OrigoIDEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from origoid import AsyncOrigoID

    client = AsyncOrigoID(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: OrigoIDEnvironment = OrigoIDEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._authentication: typing.Optional[AsyncAuthenticationClient] = None
        self._renapo: typing.Optional[AsyncRenapoClient] = None
        self._social_security: typing.Optional[AsyncSocialSecurityClient] = None
        self._ine: typing.Optional[AsyncIneClient] = None
        self._biometrics: typing.Optional[AsyncBiometricsClient] = None
        self._compliance: typing.Optional[AsyncComplianceClient] = None
        self._email: typing.Optional[AsyncEmailClient] = None
        self._proof_of_address: typing.Optional[AsyncProofOfAddressClient] = None
        self._fiscal: typing.Optional[AsyncFiscalClient] = None
        self._banking: typing.Optional[AsyncBankingClient] = None

    @property
    def authentication(self):
        if self._authentication is None:
            from .authentication.client import AsyncAuthenticationClient  # noqa: E402

            self._authentication = AsyncAuthenticationClient(client_wrapper=self._client_wrapper)
        return self._authentication

    @property
    def renapo(self):
        if self._renapo is None:
            from .renapo.client import AsyncRenapoClient  # noqa: E402

            self._renapo = AsyncRenapoClient(client_wrapper=self._client_wrapper)
        return self._renapo

    @property
    def social_security(self):
        if self._social_security is None:
            from .social_security.client import AsyncSocialSecurityClient  # noqa: E402

            self._social_security = AsyncSocialSecurityClient(client_wrapper=self._client_wrapper)
        return self._social_security

    @property
    def ine(self):
        if self._ine is None:
            from .ine.client import AsyncIneClient  # noqa: E402

            self._ine = AsyncIneClient(client_wrapper=self._client_wrapper)
        return self._ine

    @property
    def biometrics(self):
        if self._biometrics is None:
            from .biometrics.client import AsyncBiometricsClient  # noqa: E402

            self._biometrics = AsyncBiometricsClient(client_wrapper=self._client_wrapper)
        return self._biometrics

    @property
    def compliance(self):
        if self._compliance is None:
            from .compliance.client import AsyncComplianceClient  # noqa: E402

            self._compliance = AsyncComplianceClient(client_wrapper=self._client_wrapper)
        return self._compliance

    @property
    def email(self):
        if self._email is None:
            from .email.client import AsyncEmailClient  # noqa: E402

            self._email = AsyncEmailClient(client_wrapper=self._client_wrapper)
        return self._email

    @property
    def proof_of_address(self):
        if self._proof_of_address is None:
            from .proof_of_address.client import AsyncProofOfAddressClient  # noqa: E402

            self._proof_of_address = AsyncProofOfAddressClient(client_wrapper=self._client_wrapper)
        return self._proof_of_address

    @property
    def fiscal(self):
        if self._fiscal is None:
            from .fiscal.client import AsyncFiscalClient  # noqa: E402

            self._fiscal = AsyncFiscalClient(client_wrapper=self._client_wrapper)
        return self._fiscal

    @property
    def banking(self):
        if self._banking is None:
            from .banking.client import AsyncBankingClient  # noqa: E402

            self._banking = AsyncBankingClient(client_wrapper=self._client_wrapper)
        return self._banking


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: OrigoIDEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
