# This file was auto-generated by Fern from our API Definition.

import typing
from .environment import OrigoIDEnvironment
import httpx
from .core.client_wrapper import SyncClientWrapper
from .authentication.client import AuthenticationClient
from .renapo.client import RenapoClient
from .imss.client import ImssClient
from .ine.client import IneClient
from .biometrics.client import BiometricsClient
from .compliance.client import ComplianceClient
from .email.client import EmailClient
from .proof_of_address.client import ProofOfAddressClient
from .sat.client import SatClient
from .core.client_wrapper import AsyncClientWrapper
from .authentication.client import AsyncAuthenticationClient
from .renapo.client import AsyncRenapoClient
from .imss.client import AsyncImssClient
from .ine.client import AsyncIneClient
from .biometrics.client import AsyncBiometricsClient
from .compliance.client import AsyncComplianceClient
from .email.client import AsyncEmailClient
from .proof_of_address.client import AsyncProofOfAddressClient
from .sat.client import AsyncSatClient


class OrigoID:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : OrigoIDEnvironment
        The environment to use for requests from the client. from .environment import OrigoIDEnvironment



        Defaults to OrigoIDEnvironment.DEFAULT



    api_key : str
    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from origoid import OrigoID

    client = OrigoID(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: OrigoIDEnvironment = OrigoIDEnvironment.DEFAULT,
        api_key: str,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self.authentication = AuthenticationClient(client_wrapper=self._client_wrapper)
        self.renapo = RenapoClient(client_wrapper=self._client_wrapper)
        self.imss = ImssClient(client_wrapper=self._client_wrapper)
        self.ine = IneClient(client_wrapper=self._client_wrapper)
        self.biometrics = BiometricsClient(client_wrapper=self._client_wrapper)
        self.compliance = ComplianceClient(client_wrapper=self._client_wrapper)
        self.email = EmailClient(client_wrapper=self._client_wrapper)
        self.proof_of_address = ProofOfAddressClient(client_wrapper=self._client_wrapper)
        self.sat = SatClient(client_wrapper=self._client_wrapper)


class AsyncOrigoID:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : OrigoIDEnvironment
        The environment to use for requests from the client. from .environment import OrigoIDEnvironment



        Defaults to OrigoIDEnvironment.DEFAULT



    api_key : str
    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from origoid import AsyncOrigoID

    client = AsyncOrigoID(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: OrigoIDEnvironment = OrigoIDEnvironment.DEFAULT,
        api_key: str,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self.authentication = AsyncAuthenticationClient(client_wrapper=self._client_wrapper)
        self.renapo = AsyncRenapoClient(client_wrapper=self._client_wrapper)
        self.imss = AsyncImssClient(client_wrapper=self._client_wrapper)
        self.ine = AsyncIneClient(client_wrapper=self._client_wrapper)
        self.biometrics = AsyncBiometricsClient(client_wrapper=self._client_wrapper)
        self.compliance = AsyncComplianceClient(client_wrapper=self._client_wrapper)
        self.email = AsyncEmailClient(client_wrapper=self._client_wrapper)
        self.proof_of_address = AsyncProofOfAddressClient(client_wrapper=self._client_wrapper)
        self.sat = AsyncSatClient(client_wrapper=self._client_wrapper)


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: OrigoIDEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
